---
title: "Calorie Calculator"
format: html
---

# Introduction

In this project we will be creating a calorie calculator to aid us in achieving our weight loss/gain goals

# Basal Metabolic Rate

Mifflin-St Jeor Equation:

For men:
BMR = 10W + 6.25H - 5A + 5

For women:
BMR = 10W + 6.25H - 5A - 161

```{r}
ComputeBMR = function(weight = 140, height = 65, age = 30, gender = "male") {
  
  # Convert from imperial to metric
  
  weight = weight*0.45359237
  height = height*2.54
    
  if (gender == "male") {
    bmr = 10*weight + 6.25*height - 5*age + 5
  } else if (gender == "female") {
    bmr = 10*weight + 6.25*height - 5*age - 161
  }
  
  return(bmr)
}
```

```{r}
sedentary = .20
light_exercise = .375
moderate_exercise = .5
heavy_exercise = .7
athlete = .9
```


```{r}
my_bmr = ComputeBMR(weight = 136, height = 65, age = 32, gender = "male")

my_activity_level = moderate_exercise
my_bmr
```

```{r}
cat("sedentary:", my_bmr + my_bmr*.2,"\n")
cat("light exercise:", my_bmr + my_bmr*.375,"\n")
cat("moderate exercise:", my_bmr + my_bmr*.5,"\n")
cat("heavy exercise:", my_bmr + my_bmr*.7,"\n")
cat("athlete:", my_bmr + my_bmr*.9)
```


```{r}
my_bmr + my_bmr*my_activity_level
```

```{r}
my_weight = 135
current_bf_percentage = .15
goal_bf_percentage = .11
lean_mass = my_weight - my_weight*current_bf_percentage
```



```{r}
bodyweight_goal = (lean_mass/(1 - goal_bf_percentage))
bodyweight_goal
```

```{r}
my_weight - bodyweight_goal
```

```{r}
weeks_to_reach_goal = (my_weight - bodyweight_goal)/(.75)
weeks_to_reach_goal
```

```{r}
todays_date = as.Date("2024-6-27")
todays_date
```

```{r}
todays_date + weeks_to_reach_goal*7
```

# Data Table

```{r}
number_of_weeks = ceiling(weeks_to_reach_goal)
```

```{r}
todays_date + number_of_weeks*7
```

```{r}
todays_date
```

```{r}
DATE = seq(todays_date, todays_date + number_of_weeks*7, by = "week")
DATE

```

```{r}
length_of_df = length(DATE)
```

```{r}
my_weight
```

```{r}
seq(135, 130,by= -.75)
```

```{r}
WEIGHT = seq(my_weight,bodyweight_goal -.75,by = -.75)
WEIGHT
```

```{r}
(1 - lean_mass/WEIGHT)
```

